version: '3.8'

services:
  labotech:
    build:
      context: .
      target: dev
    container_name: labotech-dev
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./src:/app/src
      - ./routes:/app/routes
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    command: npx nodemon src/index.js
    restart: unless-stopped
